### ISSUE TITLE
Grasshopper_Toolkit: Grasshopper objects are modified during a solution

### ISSUE THREAD

**Issue by adecler** [BHoM/Grasshopper_Toolkit#314]
It seems that we now have an error message every time we delete a (group of) component(s) that is feeding into others:

![image](https://user-images.githubusercontent.com/16853390/50878368-54219f80-1411-11e9-8cbe-e8b34bc0d836.png)

**Comment by epignatelli** [comment]
Uhm, it looks like there is a solution in any of the component that generates this exception.
Is this happening upstream an `Explode` component?

**Comment by adecler** [comment]
it doesn't have to, it happens either way. Give it a try. It should be pretty much impossible not to replicate.

**Comment by epignatelli** [comment]
Linking to #310, I think is issue is a symptom of a wider problem.
When we expire the solution in the way below, we are not allowed to modify the grasshopper components. 
We do it in the `Explode`: it needs to calculate the outputs before knowing the name of the output parameter. We register the output parameters while the solution is still running. If it happens to have any component downstream, connected to the modified parameter of the explode, Grasshopper will complain.

So, in particular, removing the fix for #302 from #310 solves #314.
Although, in general, the fact that we are triggering a solution computation doesn't allow us to make any action on parameters.


https://github.com/BHoM/Grasshopper_Toolkit/blob/9ac0513910a2297c1fac7e7ed57fddf1254ff1fd/Grasshopper_UI/2.1/Templates/CallerComponent.cs#L104-L106

@al-fisher @rwemay
