### ISSUE TITLE
Grasshopper_Toolkit: `object` type parameter are exposed as ScriptVariable

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Grasshopper_Toolkit#372]
But the backend method does not offer an overload if you tick the `List` checkbox

**Comment by adecler** [comment]
@epignatelli , can you give a bit more details on this issue?

**Comment by epignatelli** [comment]
Whenever we expose a method in Grasshopper, if a parameter is of type `object`, the BHoM_UI will create a `Param_ScriptVariable` parameter for the component. This has few contingent issues, like having some of the options of the `Param_ScriptVariable`, `List` access checkbox.

e.g.
The method `Bar(object foo)` will be exposed in Grasshopper with a component with one input. The input is a `GH_Parameter` object, specifically a `Param_ScriptVariable` object.

Since `object` is the most generic type for classes, the most intuitive convesion rule would be to create a _data_ parameter.

However, at the time of raising the issue, this fix would have broken a lot of scripts. Maybe with the Versionin_Toolkit this is easier to act, if we want.

**Comment by adecler** [comment]
Hmm OK, then for me the important part of this issue is "_But the backend method does not offer an overload if you tick the List checkbox_" from your original comment.

Replacing the `ParamScriptVariable` is as simple as doing this:

![image](https://user-images.githubusercontent.com/16853390/72129421-21f2a700-33b1-11ea-99e9-56c31ca751c8.png)

I have tested it and it doesn't break old script (they just still use the ScriptVariable param.

But
- This means `SetProperty` would now need to enforce the use of a `Param_ScriptVariable` for its `Value' input (probably other component but that's the obvious case that comes to mind)
- If we have methods in the engine that take objects as inputs but can differentiate between list and single object, we would literally remove the only way for the user to make that work

So I am not clear why you would like to do that.

We actually have a way to handle the user ticking that box through the `OnGrasshopperUpdates` method. It just happens that it is only used by `SetProperty` and `CreateCustom` components at the moment. I cannot think of a reason why we shouldn't extend that too all change of parameters. What do you think ?

**Comment by adecler** [comment]
Closing this as it has become stale and I don't see the use of ScriptVariable as a bug. The List option is important to make sure lists can be handled properly when input type is `object`. Please raise a feature request if you think some cases should be handled better.
