### ISSUE TITLE
Grasshope_Toolkit: Method inputs cut

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Grasshopper_Toolkit#377]
Why we can not see full inputs list for all methods?

![image](https://user-images.githubusercontent.com/26113670/60130827-f222df80-978f-11e9-9b9e-be0e905063bb.png)

**Comment by alelom** [comment]
Unfortunately I couldn't repro:
![image](https://user-images.githubusercontent.com/6352844/60170602-a9efd580-9800-11e9-92c4-83af1abcf829.png)

**Comment by epignatelli** [comment]
Hey! My Grasshopper is ok as well. Does this happen also in Dynamo ?
![image](https://user-images.githubusercontent.com/26899347/60171081-c9d3c900-9801-11e9-9e43-2c6479a54fb5.png)

**Comment by michaldengusiak** [comment]
in Dynamo `Ctrl + Shift + B` is disabled but I placed `Convert ` and type in search
it is Correct
![image](https://user-images.githubusercontent.com/26113670/60174560-34d4ce00-9809-11e9-981b-a4880646aa09.png)


Excel
 it is Correct
![image](https://user-images.githubusercontent.com/26113670/60174648-6352a900-9809-11e9-997a-15f15cc74606.png)

I rebuild all again and here:
when I place Convert and search is correct
![image](https://user-images.githubusercontent.com/26113670/60174760-ab71cb80-9809-11e9-8862-abb9959ecd8a.png)
when i use `Ctrl + Shift + B` is wrong
![image](https://user-images.githubusercontent.com/26113670/60174787-bf1d3200-9809-11e9-97c3-b2b79902188a.png)

**Comment by epignatelli** [comment]
I honestly have no idea where this is coming from, sorry about that.
The menu is not even coded in the specific UIs, but in the abstract `BHoM_UI`.

**Comment by michaldengusiak** [comment]
ok this is now identified this was due to scaling I had 120% when I change to 100%

![image](https://user-images.githubusercontent.com/26113670/60673972-faa2a680-9e70-11e9-960b-6336c719417d.png)


![image](https://user-images.githubusercontent.com/26113670/60673933-e068c880-9e70-11e9-8119-cab3e0f9df1e.png)

**Comment by rwemay** [comment]
Hi @michaldengusiak , I don't think this issue is specific to BHoM, rather it's windows scaling/display settings. I helped someone yesterday with this - it's basically a magic formula/combination of windows display settings that works. You'll find it's not just the menus, but all text in Grasshopper is difficult to read (and some other apps).

**Comment by alelom** [comment]
Now that I think of it, @PaulPoinet had a similar issue I remember. In his case, the list of methods appeared extremely tiny, and the issue was actually more serious than a few characters cut-off.

@PaulPoinet, would you mind sharing a screenshot of your case here, specifying whats the Windows zoom level in your case? 

I think it would be good to keep track of this -- even if it's not an issue specific to BHoM, we might later find out of a workaround for people having trouble with it.

**Comment by epignatelli** [comment]
Thanks for the help all! 
Just so as you know, @michaldengusiak opened https://github.com/BHoM/BHoM_UI/issues/114 to track the problem down!
