### ISSUE TITLE
Grasshopper_Toolkit: Internalise BHoM object not working

### ISSUE THREAD

**Issue by rwemay** [BHoM/Grasshopper_Toolkit#429]
#### Description:

Internalise works whilst the script is open, but if you save, close and reopen the same script, you get GH_ObjectWrappers instead of the original objects. 

#### How to replicate:

Internalise some objects into a Data collection, save, close and reopen. 

![before](https://user-images.githubusercontent.com/15233608/68141429-6aab6100-ff25-11e9-823a-a4e91075ba81.PNG)

![after](https://user-images.githubusercontent.com/15233608/68141434-6e3ee800-ff25-11e9-9ff8-0df8c041e2a2.PNG)

**Comment by epignatelli** [comment]
Hi Rob, what kind of parameter is the "BHoM Framing" and which object does the class you're trying to store inherits from? Is it `IObject` or `BHoMObject`?

**Comment by IsakNaslundBh** [comment]
Think this in an issue when you pull things from an adapter. As it outputs `object` GH does not know that it should wrap it in a BHoM GH_Goo and hence it fails to serialise. If you output obejcts from an adapter, then put them in a BHoMObejct parameter, then in a data parameterthey serialise fine in the data parameter(or BHoMParameter for that matter).

Not sure how easy it is to fix as might need to reach the code for the generic Goo somehow. Could also potentially do some type checking on the outputs from the pull to ensure they end up in correct Goo, still in a generic parameter.

**Comment by adecler** [comment]
I honestly don't know how to fix this. The Data component is not created by us so we have little control on how it behaves. I have placed breakpoints everywhere I could think of to try and see if it was at least hitting some of our code when deserialising but no success there.

All I could say is use the `BHoMObjectParam` or `IObjectParam` component when you are internalising data. This is obviously not ideal but I don't see what else to do.

@epignatelli , I leave this open in case you want to give it a shot too.

**Comment by IsakNaslundBh** [comment]
@adecler Not sure if this solves the full extent of the problem, but would it be possible to make sure BHoMObjects always ends up in a `GH_BHoMGoo`, geometry in `BH_IBHoMGeometry` and all other `Iobjects` in `GH_IObject` as their Goo assignment when being retuirned from any of our methods. This is, even if the method returns a system object, or list of system object? Pull could be used as a good example case for this.

Think the problem is that they never end up in this goo, but stays in so generic one Grasshopper assigns in lack of a better option. 

Saying all of this, not how easy this would be to solve, if at all doable.

**Comment by epignatelli** [comment]
I gave it a go and I think that the only level we can act on is the Grasshopper serialization - `GH_Chunk`. The object is passed in the `Write` and `Read` methods (`IReader` and `IWriter`). 

We can find a way of passing that to the parameters - I think it would require adding some checks and swtiches to the `Copy` methods of the `GH_DocumentIO`. But that's very deep into Grashopper, I'd rather add a warning somewhere when you are passing an `IObject` into a generic grasshopper parameter.

**Comment by adecler** [comment]
Now working on the master:

![image](https://user-images.githubusercontent.com/16853390/108965147-6cb7a700-76b7-11eb-958b-9dfd56774c73.png)

**Comment by IsakNaslundBh** [comment]
Just to be clear on the issue here (think it still potentially has been solved) The above screenshot @adecler was working before as well, as they always contained BHoMObjects/Geometry wrapped up in our own Goos. The problem was when you had run some component that returned `System.Object` such as the Pull for example. Then our objects ended up in some generic GH_Goo, and was not able to be serialised in the DataParameter, _unless_ you first passed them through some of the BHoM parameters.

I think the addition of our own VariableGoo and Parameter might have sorted this issue, but do not think the screenshot is enough to test that unfortunately.

**Comment by adecler** [comment]
Thanks @IsakNaslundBh , yes I have double-checked:

![image](https://user-images.githubusercontent.com/16853390/108976220-40edee80-76c2-11eb-94ab-18b872c3042f.png)
