### ISSUE TITLE
Grasshopper_Toolkit: Casting explicit objects

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Grasshopper_Toolkit#455]
#### Description:
Passing a Points, Curves or Surfaces into a 'toJson' component and then back out of a 'fromJson' component fails.

#### How to replicate:
See test file

#### Expected behaviour:
Objects are correctly return by 'fromJson' component.

#### Test file(s):

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FGrasshopper%5FToolkit%2FGrasshopper%5FToolkit%2DIssue455%2DCastingExplicitObjects&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

**Comment by epignatelli** [comment]
The script is trying to serialise and deserialise rhinoceros objects. The `FromJson` only handles `IObjects` (bhom objects), because we know the target schema. Serialising objects which do not come from the BHoM library is not in our scope, unfortunately.

Solution:
You can serialise thse objects by inputting them into a `BHoMObject` parameter and serialise that one instead. 

![image](https://user-images.githubusercontent.com/26899347/72894810-fefeb600-3d13-11ea-850b-7cfb774d31f0.png)

**Comment by rwemay** [comment]
thanks @epignatelli , I see this issue is closed, just to double check - is it not useful/worth (or even possible) for us to cast geometry to BHoM on input to this/other components?

**Comment by epignatelli** [comment]
The `FromJson` component is reflecting the `BH.Engine.Serialiser.Convert.FromJson(string json)` method.
The input is only a `string` which will make sense only because there is a deserialisation logic (and adferent object schemas).

If we want to include Rhino objects in our usual `FromJson` we would have to make the `Serialiser_Engine` depend on the `RhinoCommon`.
I don't think that is a way to go, or we would open the door to include any other software object into the `Serialiser_Engine`.

The other way around is to create a `FromJson` into the Rhinoceros_Engine, which I think it would make sense. That's not the easiest method to write, though. It should look into the `Serialiser_Engine`, register new conversion conventions and serialisation rules. It is doable I think, but a longer shot that it looks like.

However, that would not solve the problem of doing it with only one component (the current one). You would have to use another component. (a `Convert` most likely).

The solution to this last, is to use the same pattern we use for `IGeometry`, but I'd avoid spreading that pattern, as it is a bit of a workaround.

Does all of this make sense?

**Comment by jdarcyBHE** [comment]
Yes makes perfect sense, thanks for the explanations.
