### ISSUE TITLE
Grasshopper_Toolkit: The intellisense goes mad after restart on Rhino 5

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Grasshopper_Toolkit#538]
#### Description:

After starting GH on Rhino 5, then calling _GrasshopperUnloadPlugin and starting again, intellisense starts to harass the user:

![RevitAdapter](https://user-images.githubusercontent.com/26874773/93352336-02aef200-f83b-11ea-9e77-562cc6762b8a.gif)

Does not sounds like a prio, but would be nice to fix if easy I think.

**Comment by adecler** [comment]
I had a look and it doesn't seem to be easy. The GH wire info (extracted through reflection) that I am using to figure out its state is apparently messed up once Grasshopper is unloaded and reloaded. 

I'll see if I can find a more reliable source of info when I have the time but meanwhile the solution is simple: stop unloading Grasshopper 😋

**Comment by adecler** [comment]
Since this is a very exceptional case, a problem only with Rhino 5, and it is very difficult to solve, I suggest we close this one.

It seems that most of the issue comes from the Grasshopper side anyways as trying to call this command from Rhino 6 seems to imply 😉 

>Dear expert user, the _GrasshopperUnloadPlugin command has been deactivated because reasons. 
To be less facetious, it never really did what it claimed to do, and in the process of not-quite-doing-what-it-pretended-to-do caused more problems than it solved.
If you absolutely, positively need this feature in order to achieve and/or maintain a life worth living, please post something to this effect on https://discourse.mcneel.com/
