### ISSUE TITLE
Upgrade to latest Beta causes issues with old ghop scripts

### ISSUE THREAD

**Issue by emidio-piermarini** [BHoM/Grasshopper_Toolkit#553]
#### Description:
Found that I had to replace all the 'explode' components in this script once i updated to the latest beta.

#### Test file(s):
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Grasshopper_Toolkit/Grasshopper_Toolkit_Issue205_Upgrade%20Issue?csf=1&web=1&e=Z6PMFB

**Comment by FraserGreenroyd** [comment]
The issue described in the test file will be resolved by [this PR](https://github.com/BHoM/Versioning_Toolkit/pull/108) for the most part. However, the uncovering of this issue was only found following work done to [the Space object](https://github.com/BHoM/BHoM/pull/1108) which further changed the Space object.

Following investigation with @JohannaOlin1 and @IsakNaslundBh , upgrading the Space object from 3.2 to 3.3 is available. Upgrading from 3.3 to 4.0 causes issues which are related to [this issue on Serialiser_Engine](https://github.com/BHoM/BHoM_Engine/issues/2200) that will hopefully be resolved by the 4.0 beta (pending action from @adecler ).

If you upgrade the objects to 3.3 upgrade to 4.0 is possible manually via the `ToNewVersion` component, but should be happening automatically which is the reason for raising [this issue](https://github.com/BHoM/BHoM_Engine/issues/2200). I'm closing this issue as it is not related to Grasshopper Toolkit, and further issues to finally resolve all of the aspects of this have been raised :smile:
