### ISSUE TITLE
Rhino polylines are returned as list of points

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Grasshopper_Toolkit#587]
#### Description:

A method returning a `Rhino.Geometry.Polyline` seem to be returning a list of points instead when called via the UI.

![image](https://user-images.githubusercontent.com/22005920/104452610-88ea0380-55a3-11eb-92e9-745e56a79083.png)

Methods used:

https://github.com/BHoM/Rhinoceros_Toolkit/blob/7569d637080b7215242050933c92527ce674a62a/Rhinoceros_Engine/Create/Polyline.cs#L28-L46

Have never experienced this when a method is returning a BHoM Polyline, hence not supercritical, but something strange seem to be going on here.

#### Steps to reproduce:

Call a method returning a rhino polyline, for example Create.Random

#### Expected behaviour:

For a polyline to be returned

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/Epwow6zuX65Pr6ugM1h5Lg0BDPiCKVgGU_CqCjRASzkN7Q?e=lshLQf

**Comment by adecler** [comment]
Let me guess: the `Rhino.Geometry.Polyline` is an `IEnumerable` ?

**Comment by IsakNaslundBh** [comment]
> Let me guess: the `Rhino.Geometry.Polyline` is an `IEnumerable` ?

Yes
https://developer.rhino3d.com/api/RhinoCommon/html/T_Rhino_Geometry_Polyline.htm

**Comment by adecler** [comment]
This issue doesn't have a solution and I am not sure it should. 

The whole framework is relying on `IEnumerable` as something that should always be treated as a list. This goes as deep as `BH.Engine.Reflection.Query.UnderlyingType()`. The framework is designed to handle both BHoM and System namespaces correctly. Anything outside of that might work but is not guaranteed to. Good examples of that are the `Explode` component or the serialisation to Json.

I have however tried to handled this purely inside the Grasshopper toolkit since it is referencing the Rhinoceros dlls (see changes below). Unfortunately, this was not enough and changes to the BHoM_UI would be necessary to fix the issue. 

![image](https://user-images.githubusercontent.com/16853390/108462287-52488c80-72b7-11eb-8a59-c4c32265d1a2.png)

As you said, BHoM Polyline is working perfectly fine (as any other BHoM object) and should be the recommended workflow. 
I am closing this issue as it belongs to the same category as complaining that a Rhinoceros object doesn't explode properly. 
I wonder if we should make those methods private though.
